version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-host
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"